apiVersion: v1
kind: Service
metadata:
    name: "rktwohat-f0b0"
    labels:
        app: "rktwohat-f0b0"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "rktwohat-f0b0"